# Generated by Django 3.0.5 on 2020-05-01 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='client_ids',
        ),
        migrations.RemoveField(
            model_name='bookings',
            name='counsellor_ids',
        ),
    ]
