# Generated by Django 3.0.5 on 2020-07-22 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counsellordata',
            name='Profile_pic',
            field=models.FileField(blank=True, null=True, upload_to='counsellor_pic/'),
        ),
    ]
