# Generated by Django 3.0.5 on 2020-04-16 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_auto_20200416_0751'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientdata',
            fields=[
                ('Name', models.CharField(max_length=100)),
                ('Gender', models.CharField(choices=[('0', 'Male'), ('1', 'Female'), ('2', 'Other')], max_length=32)),
                ('Age', models.IntegerField()),
                ('Email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('State', models.CharField(max_length=50, null=True)),
                ('City', models.CharField(max_length=50, null=True)),
                ('Marital_Status', models.CharField(choices=[('0', 'Single'), ('1', 'Commited'), ('2', 'Divorced'), ('3', 'Married')], max_length=32)),
                ('Educational_Status', models.CharField(choices=[('0', '10th'), ('1', '12th'), ('2', 'Graduate'), ('3', 'Post-Graduate'), ('4', 'Doctorate'), ('5', 'Post-Doc')], max_length=32)),
            ],
        ),
        migrations.AlterField(
            model_name='description',
            name='Email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.Clientdata'),
        ),
        migrations.DeleteModel(
            name='Userdata',
        ),
    ]
