# Generated by Django 3.0.5 on 2020-04-24 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_auto_20200422_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='activeclient',
            name='Booking_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='activecounsellor',
            name='Booking_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='counsellordata',
            name='Consultation_end',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='counsellordata',
            name='Consultation_start',
            field=models.TimeField(null=True),
        ),
    ]
