# Generated by Django 3.0.5 on 2020-07-22 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_auto_20200722_1302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='counsellordata',
            name='Profile_pic',
        ),
        migrations.AddField(
            model_name='counsellordata',
            name='profilepicname',
            field=models.TextField(default='-'),
        ),
        migrations.AddField(
            model_name='counsellordata',
            name='profilepicurl',
            field=models.TextField(default='-'),
        ),
    ]
