# Generated by Django 3.0.5 on 2020-05-01 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_auto_20200501_0641'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='client_key',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookings',
            name='counsellor_key',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
