# Generated by Django 3.0.5 on 2020-07-22 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_auto_20200722_1314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='description',
            name='extra_data',
        ),
        migrations.RemoveField(
            model_name='sessionnotes',
            name='file',
        ),
        migrations.AddField(
            model_name='description',
            name='filename',
            field=models.TextField(default='-'),
        ),
        migrations.AddField(
            model_name='description',
            name='fileurl',
            field=models.TextField(default='-'),
        ),
        migrations.AddField(
            model_name='sessionnotes',
            name='filename',
            field=models.TextField(default='-'),
        ),
        migrations.AddField(
            model_name='sessionnotes',
            name='fileurl',
            field=models.TextField(default='-'),
        ),
    ]
