# Generated by Django 3.0.5 on 2020-07-22 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_auto_20200722_1924'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extra_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='-')),
                ('content', models.TextField(default='-')),
            ],
        ),
        migrations.CreateModel(
            name='Motivation_large',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote1', models.TextField(default='-')),
                ('quote2', models.TextField(default='-')),
                ('picture', models.FileField(blank=True, null=True, upload_to='client/uploads')),
                ('article_link', models.TextField(default='-')),
            ],
        ),
        migrations.CreateModel(
            name='Motivation_small',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brief', models.TextField(default='-')),
                ('picture', models.FileField(blank=True, null=True, upload_to='client/uploads')),
                ('article_link', models.TextField(default='-')),
            ],
        ),
    ]
