# Generated by Django 3.0.5 on 2020-05-12 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
