# Generated by Django 3.0.5 on 2020-07-22 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_extra_info_motivation_large_motivation_small'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motivation_large',
            name='picture',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
