# Generated by Django 3.0.5 on 2020-04-17 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_auto_20200416_1114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='description',
            name='Email',
        ),
    ]
