# Generated by Django 3.0.5 on 2020-05-12 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_post_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='brief',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
