# Generated by Django 3.0.5 on 2020-05-12 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_post_brief'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='brief',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
