# Generated by Django 3.0.5 on 2020-07-22 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_auto_20200722_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motivation_large',
            name='picture',
            field=models.FileField(blank=True, null=True, upload_to='uploads'),
        ),
    ]
