# Generated by Django 3.0.5 on 2020-04-17 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_remove_description_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description',
            name='Message',
            field=models.CharField(max_length=1000),
        ),
    ]
