# Generated by Django 3.0.5 on 2020-07-22 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_auto_20200722_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='motivation_small',
            name='title',
            field=models.TextField(default='-'),
        ),
    ]
