# Generated by Django 3.0.5 on 2020-04-17 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_remove_description_extra_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='description',
            name='extra_data',
            field=models.FileField(null=True, upload_to='client/uploads'),
        ),
    ]
