# Generated by Django 3.0.5 on 2020-05-20 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0009_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.TimeField(auto_now=True, null=True),
        ),
    ]
