# Generated by Django 3.0.5 on 2020-07-22 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0009_about_us_big_about_us_small_team_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team_details',
            name='email',
            field=models.CharField(max_length=300),
        ),
    ]
