# Generated by Django 3.0.5 on 2020-04-18 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0009_description_extra_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdata',
            name='Educational_Status',
            field=models.CharField(choices=[('0', '10th Pass'), ('1', '12th Pass'), ('2', 'Graduate'), ('3', 'Post-Graduate'), ('4', 'Doctorate'), ('5', 'Post-Doc')], max_length=32),
        ),
        migrations.AlterField(
            model_name='clientdata',
            name='Gender',
            field=models.CharField(choices=[('0', 'Male'), ('1', 'Female'), ('2', 'Others')], max_length=32),
        ),
    ]
