# Generated by Django 3.0.5 on 2020-07-22 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0010_auto_20200722_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='team_details',
            name='picture',
            field=models.FileField(blank=True, null=True, upload_to='uploads'),
        ),
    ]
