# Generated by Django 3.0.5 on 2020-07-22 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0011_team_details_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem_reports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='-')),
                ('brief', models.TextField(default='-')),
            ],
        ),
    ]
