# Generated by Django 3.0.5 on 2020-04-20 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client', '0012_auto_20200420_1047'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counsellordata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Gender', models.IntegerField(choices=[(0, 'Male'), (1, 'Female'), (2, 'Other')], max_length=32)),
                ('Age', models.IntegerField(blank=True, null=True)),
                ('Profile_pic', models.FileField(blank=True, null=True, upload_to='')),
                ('Email', models.EmailField(max_length=254)),
                ('State', models.CharField(blank=True, max_length=50, null=True)),
                ('City', models.CharField(blank=True, max_length=50, null=True)),
                ('Education', models.CharField(blank=True, max_length=300, null=True)),
                ('Expertise', models.CharField(blank=True, max_length=200, null=True)),
                ('Summary', models.CharField(blank=True, max_length=1000, null=True)),
                ('User', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
