# Generated by Django 3.0.5 on 2020-05-23 20:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client', '0013_auto_20200524_0120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videocalllink',
            old_name='User',
            new_name='counsellor',
        ),
        migrations.AddField(
            model_name='videocalllink',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cl_video', to=settings.AUTH_USER_MODEL),
        ),
    ]
