# Generated by Django 3.0.5 on 2020-07-31 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0014_faq_big_faq_small_queries'),
    ]

    operations = [
        migrations.RenameField(
            model_name='queries',
            old_name='brief',
            new_name='question',
        ),
        migrations.RemoveField(
            model_name='queries',
            name='title',
        ),
    ]
