# Generated by Django 3.0.5 on 2020-04-20 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0014_auto_20200420_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counsellordata',
            name='Gender',
            field=models.IntegerField(choices=[(0, 'Male'), (1, 'Female'), (2, 'Other')]),
        ),
    ]
