# Generated by Django 3.0.5 on 2020-05-24 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0015_auto_20200525_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdata',
            name='Gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=32),
        ),
    ]
