# Generated by Django 3.0.5 on 2020-05-24 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0016_auto_20200525_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdata',
            name='Educational_Status',
            field=models.CharField(choices=[('10th Pass', '10th Pass'), ('12th Pass', '12th Pass'), ('Graduate', 'Graduate'), ('Post_Graduate', 'Post_Graduate'), ('Doctorate', 'Doctorate'), ('Post_Doc', 'Post_Doc')], max_length=32),
        ),
        migrations.AlterField(
            model_name='clientdata',
            name='Marital_Status',
            field=models.CharField(choices=[('Single', 'Single'), ('Commited', 'Commited'), ('Divorced', 'Divorced'), ('Married', 'Married')], max_length=32),
        ),
    ]
