# Generated by Django 3.0.5 on 2020-05-25 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client', '0017_auto_20200525_0024'),
    ]

    operations = [
        migrations.CreateModel(
            name='sessionNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=200, null=True)),
                ('time', models.TimeField(auto_now=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='client/uploads')),
                ('about', models.TextField(blank=True, null=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sess_cl', to=settings.AUTH_USER_MODEL)),
                ('counsellor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sess_coun', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
