# Generated by Django 3.0.5 on 2020-05-25 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0018_sessionnotes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sessionnotes',
            old_name='Name',
            new_name='title',
        ),
    ]
