# Generated by Django 3.0.5 on 2020-05-27 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0020_auto_20200527_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionnotes',
            name='time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
