# Generated by Django 3.0.5 on 2020-05-27 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0021_auto_20200527_1311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='Name',
        ),
        migrations.AddField(
            model_name='post',
            name='time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
