# Generated by Django 3.0.5 on 2020-05-27 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0022_auto_20200527_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counsellordata',
            name='Gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=32),
        ),
    ]
