# Generated by Django 3.0.5 on 2020-05-27 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0024_activebookings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activecounsellor',
            name='Counsellor',
        ),
        migrations.RemoveField(
            model_name='activecounsellor',
            name='user',
        ),
        migrations.DeleteModel(
            name='ActiveClient',
        ),
        migrations.DeleteModel(
            name='ActiveCounsellor',
        ),
    ]
