# Generated by Django 3.0.5 on 2020-04-16 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Userdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Gender', models.CharField(choices=[(0, 'Male'), (1, 'Female'), (2, 'Other')], max_length=32)),
                ('Age', models.IntegerField()),
                ('Email', models.EmailField(max_length=254)),
                ('State', models.CharField(max_length=50, null=True)),
                ('City', models.CharField(max_length=50, null=True)),
                ('Educational_Status', models.CharField(choices=[(0, '10th'), (1, '12th'), (2, 'Graduate'), (3, 'Post-Graduate'), (4, 'Doctorate'), (5, 'Post-Doc')], max_length=32)),
            ],
        ),
    ]
