# Generated by Django 3.0.5 on 2020-04-16 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counsellor', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Userdata',
            new_name='Counsellordata',
        ),
    ]
