# Generated by Django 3.0.5 on 2020-04-16 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counsellor', '0002_auto_20200416_1109'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Counsellordata',
            new_name='Userdata',
        ),
    ]
