# Generated by Django 3.0.5 on 2020-04-17 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counsellor', '0006_remove_counsellordata_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='counsellordata',
            name='Educational_Status',
        ),
        migrations.AddField(
            model_name='counsellordata',
            name='Education',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='counsellordata',
            name='Expertise',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='counsellordata',
            name='Profile_pic',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='counsellordata',
            name='Summary',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='counsellordata',
            name='Age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='counsellordata',
            name='Gender',
            field=models.IntegerField(choices=[(0, 'Male'), (1, 'Female'), (2, 'Other')], max_length=32),
        ),
    ]
