# Generated by Django 3.0.5 on 2020-04-18 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counsellor', '0008_auto_20200417_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counsellordata',
            name='Gender',
            field=models.IntegerField(choices=[(0, 'Male'), (1, 'Female'), (2, 'Other')]),
        ),
    ]
