# Generated by Django 3.0.5 on 2020-04-20 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counsellor', '0009_counsellordata_user'),
        ('counsellor', '0009_auto_20200418_1528'),
    ]

    operations = [
    ]
