# Generated by Django 3.0.5 on 2020-04-20 10:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('counsellor', '0009_counsellordata_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counsellordata',
            name='User',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
