# Generated by Django 3.0.5 on 2020-04-20 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counsellor', '0010_auto_20200420_1047'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Counsellordata',
        ),
    ]
